import { type NextPage } from "next";
import { signIn } from "next-auth/react";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>twidle</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen w-full items-center justify-center">
        {/* + "bg-gradient-to-b from-blue-900 to-[#15162c]"> */}
        <button onClick={() => { void signIn(); return }}>
          Test
        </button>
      </main>
    </>
  );
};

export default Home;
