import { type NextPage } from "next";
import Head from "next/head";
import { useSession, signIn, signOut } from "next-auth/react";
import { useState, useEffect } from "react";
import { Task } from "@prisma/client";

const Home: NextPage = () => {
  const { data: session } = useSession();
  const [tasks, setTasks] = useState<Task[]>([]);
  useEffect(() => {
    async function fetchTasks() {
      if (session) {
        const resp = await fetch(`/api/users/${session.user.id}`);
        // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
        const tasks: Task[] = await resp.json();
        setTasks(tasks);
      }
    }
    void fetchTasks();
  }, [session]);
  if (session) {
    return (
      <>
        Signed in as {session.user.email} <br />
        <button onClick={() => void signOut()}>Sign out</button>
        {tasks.map((task, idx) => {
          return <div key={idx}>
            <div>
              { task.title }
            </div>
          </div>;
        })}
      </>
    );
  } else {
    return (
      <>
        <Head>
          <title>twidle</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="flex min-h-screen w-full items-center justify-center">
          {/* + "bg-gradient-to-b from-blue-900 to-[#15162c]"> */}
          <button
            onClick={() => {
              void signIn();
              return;
            }}
          >
            Log in
          </button>
        </main>
      </>
    );
  }
};

export default Home;
