import { type NextPage } from "next";
import Head from "next/head";
import { useSession, signIn, signOut } from "next-auth/react";
import Link from "next/link";

const Home: NextPage = () => {
  const { data: session } = useSession();
  if (session) {
    return (
      <>
        Signed in as {session.user.email} <br />
        <button onClick={() => void signOut()}>Sign out</button>
        <div>
          <Link href="/tasks">Go to Task Dashboard</Link>
        </div>
      </>
    );
  } else {
    return (
      <>
        <Head>
          <title>twidle</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="flex min-h-screen w-full items-center justify-center">
          {/* + "bg-gradient-to-b from-blue-900 to-[#15162c]"> */}
          <button
            onClick={() => {
              void signIn();
              return;
            }}
          >
            Log in
          </button>
        </main>
      </>
    );
  }
};

export default Home;
